lutece-platform/lutece-core

src/java/fr/paris/lutece/portal/service/portal/PortalMenuService.java
src/test/java/fr/paris/lutece/portal/service/AllTests.java
src/test/java/fr/paris/lutece/portal/service/portal/PortalMenuServiceTest.java

and add a test which fails on the page modification part when the patch to PortalMenuService is *not* applied

Lutece 1847 : Make PortalMenuService react to page events

---

src/java/fr/paris/lutece/portal/web/xpages/SiteMapCacheService.java
src/test/java/fr/paris/lutece/portal/web/xpages/SiteMapAppTest.java

and add a test, which fails on the page modification part when the SiteMapCacheService patch is *not* applied

Lutece 1848 : make SiteMapApp react to page events

---

webapp/WEB-INF/templates/admin/site/admin_page_block_property.html

This make the validation and cancel buttons visible at all times.

LUTECE-1849 : remove stray div

---

src/java/fr/paris/lutece/portal/service/daemon/AppDaemonService.java
src/java/fr/paris/lutece/portal/service/daemon/DaemonThread.java
src/java/fr/paris/lutece/portal/service/daemon/DaemonThreadFactory.java
src/java/fr/paris/lutece/portal/service/init/AppInfo.java
src/java/fr/paris/lutece/portal/service/init/AppInit.java
webapp/WEB-INF/conf/core.xml
webapp/WEB-INF/conf/daemons.properties

Daemon Threads recover their name after being released by a task.
Thread names "pool-1-thread-3" renamed "Lutece-DaemonsPool-Thread-3"
Webapp main thread renamed "Lutece-MainThread"

LUTECE-1861 : Daemon Threads enhancements

---

src/java/fr/paris/lutece/portal/service/plugin/Plugin.java
src/java/fr/paris/lutece/portal/service/plugin/PluginFile.java
src/java/fr/paris/lutece/portal/service/plugin/PluginService.java
src/java/fr/paris/lutece/portal/service/plugin/plugin-digester-rules.xml
src/java/fr/paris/lutece/portal/web/includes/LinksInclude.java
webapp/WEB-INF/conf/core.xml
webapp/css/page_template_styles.css
webapp/css/page_template_styles_admin.css

* Add a mode attribute in the plugin's xml file
* take it into account when including stylesheets and javascript files
* split the core admin styles into their own stylesheet

Lutece 1864 : Add the possibility for a plugin js and css files to target a mode

---

src/java/fr/paris/lutece/portal/resources/site_messages.properties
src/java/fr/paris/lutece/portal/resources/site_messages_fr.properties
src/java/fr/paris/lutece/portal/service/page/PageService.java
webapp/WEB-INF/templates/admin/column_outline.html
webapp/css/page_template_styles_admin.css

the display is done on hover. Tested with Firefox chrome and Safari.

LUTECE-1868 : In admin mode, display column outline and identification

---

src/java/fr/paris/lutece/portal/business/page/Page.java
src/java/fr/paris/lutece/portal/business/page/PageDAO.java

This allows clients of the Page object to detect if the page was
reparented.

CHILDPAGES-7 : Give access to the parent page ID as stored in the DB

---

src/java/fr/paris/lutece/portal/service/init/AppInitListener.java
src/java/fr/paris/lutece/portal/service/spring/SpringContextService.java

This allows disposable beans to release their resources

LUTECE-1890 : Close the spring context on app shutdown

---

src/java/fr/paris/lutece/portal/service/includes/PageIncludeEntry.java
src/java/fr/paris/lutece/portal/service/includes/PageIncludeService.java
src/java/fr/paris/lutece/portal/service/plugin/plugin-digester-rules.xml
src/test/java/fr/paris/lutece/portal/service/includes/PageIncludeServiceTest.java
src/test/java/fr/paris/lutece/portal/service/plugin/PluginFileTest.java
src/test/resources/plugin-test.xml
webapp/WEB-INF/conf/core.xml
webapp/WEB-INF/conf/lutece.properties

And apply the possibility to the core PageIncludes via variables in lutece.properties

Lutece 1891 : Allow PageIncludes to be set as disabled in the plugin description file

---

src/java/fr/paris/lutece/portal/resources/users_messages.properties
src/java/fr/paris/lutece/portal/resources/users_messages_fr.properties
src/java/fr/paris/lutece/portal/web/user/AdminUserJspBean.java

This should help the admin user be sure that she is anonymizing the intended user.
Also display a proper message if the user to be anonymized does not exist.

LUTECE-1927 : display the first name, last name and access code of the user to be anonymized on the confirmation page

---

src/java/fr/paris/lutece/portal/business/page/PageDAO.java
src/test/java/fr/paris/lutece/portal/business/page/PageDAOTest.java

The dateUpdate field was not read, which resulted in an off by one error.
Add a test to cover this method.

LUTECE-1937 : fix page attribute reading when searching by role

---

src/java/fr/paris/lutece/portal/resources/site_messages.properties
src/java/fr/paris/lutece/portal/resources/site_messages_fr.properties
src/java/fr/paris/lutece/portal/web/admin/AdminPageJspBean.java
src/test/java/fr/paris/lutece/portal/web/admin/AdminPageJspBeanTest.java

Do more validation on the page id argument
Fix the return URL is deletion fails due to child pages.
Add a test.

LUTECE-1939 : Add the page name to the confirmation message

---

webapp/WEB-INF/templates/admin/user/attribute/create_attribute_field.html

Add name and value attributes.

LUTECE-1941 : Correctly identify the cancel button

---

src/java/fr/paris/lutece/portal/business/dashboard/AdminDashboardDAO.java
src/java/fr/paris/lutece/portal/web/dashboard/AdminDashboardJspBean.java

Same change as for LUTECE-1748

LUTECE-1944 : Allow technical dashboards to be in no column

---

src/java/fr/paris/lutece/portal/web/admin/AdminPagePortletJspBean.java
src/test/java/fr/paris/lutece/portal/web/admin/AdminPagePortletJspBeanTest.java

Add better request parameters validation.
Add tests.

LUTECE-1959 : Check rights before changing the status of a portlet

---

src/java/fr/paris/lutece/portal/web/admin/AdminPagePortletJspBean.java
src/test/java/fr/paris/lutece/portal/web/admin/AdminPagePortletJspBeanTest.java

Better validate parameters and add tests.

LUTECE-1960 : check rights before portlet deletion

---

src/java/fr/paris/lutece/portal/util/mvc/admin/MVCAdminJspBean.java
src/java/fr/paris/lutece/portal/util/mvc/xpage/MVCApplication.java
webapp/WEB-INF/templates/commons.html

J'ai ajouté des warnings pour les XPages et les AdminFeatures

LUTECE-2002 added warnings to xpages and adminfeatures

---

src/java/fr/paris/lutece/util/sql/DAOUtil.java

Improve the coverage of methods from PreparedStatement and
ResultSet in DAOUtil.

LUTECE-2006 : Add more get/set pairs to DAOUtil

---

src/java/fr/paris/lutece/portal/service/util/CryptoService.java
src/test/java/fr/paris/lutece/portal/service/util/CryptoServiceTest.java
webapp/WEB-INF/conf/lutece.properties

The key is generated on first access. If a legacy key is found in lutece.properties,
use that to preserve its past uses validity.
Add tests.

LUTECE-2022 : Generate a random crypto key and store it in Datastore

---

webapp/jsp/admin/security/ConfirmRemovePublicUrl.jsp
webapp/jsp/admin/security/DoCreatePublicUrl.jsp
webapp/jsp/admin/security/DoModifyPublicUrl.jsp
webapp/jsp/admin/security/DoRemovePublicUrl.jsp
webapp/jsp/admin/security/ManageAdvancedParameters.jsp
webapp/jsp/admin/security/ManagePublicUrl.jsp

These were probably leftovers from when plugin-mylutece was
extracted from core.

LUTECE-2014 : remove non functional and unused files

---

src/test/java/fr/paris/lutece/portal/web/user/AdminUserJspBeanTest.java
webapp/WEB-INF/templates/admin/user/create_user_default_module.html

Otherwise, it is impossible to create a new BO user

LUTECE-2082 : Correct argument types for commons.html macros

---

src/sql/build.xml
src/sql/includes/build-all.xml
src/sql/includes/build-oldstructure.xml
src/sql/includes/build-specific.xml
src/sql/includes/build-update.xml

That way, targets in them do not depend on unknown targets from build.xml

LUTECE-2078 : use extension points in included ant files

---

src/java/fr/paris/lutece/portal/service/daemon/AppDaemonService.java
src/java/fr/paris/lutece/portal/service/daemon/DaemonThread.java
src/test/java/fr/paris/lutece/portal/web/system/DaemonsJspBeanTest.java

LUTECE-2085 : Indicate that the daemon is running before scheduling it

---

src/java/fr/paris/lutece/portal/web/system/CacheJspBean.java
src/test/java/fr/paris/lutece/portal/web/system/CacheJspBeanTest.java
webapp/WEB-INF/templates/admin/system/manage_caches.html
webapp/jsp/admin/system/DoReloadProperties.jsp

This also fixes LUTECE-1855 : All state-altering actions are changed to POST.

LUTECE-2163 : Add CSRF tokens to CacheJspBean actions

---

src/java/fr/paris/lutece/portal/service/search/IndexationService.java
src/java/fr/paris/lutece/portal/web/search/SearchIndexationJspBean.java
src/test/java/fr/paris/lutece/portal/web/search/SearchIndexationJspBeanTest.java
webapp/WEB-INF/templates/admin/search/manage_search_indexation.html
webapp/WEB-INF/templates/admin/search/search_indexation_logs.html

Add a way to unregister an indexer, to allow adding and removing
a test indexer.

LUTECE-2164 : Add a CSRF token to indexation actions

---

src/java/fr/paris/lutece/portal/web/dashboard/AdminDashboardJspBean.java
src/test/java/fr/paris/lutece/portal/web/dashboard/AdminDashboardJspBeanTest.java
src/test/java/fr/paris/lutece/portal/web/dashboard/TestAdminDashboardCompoent.java
webapp/WEB-INF/templates/admin/dashboard/admin/manage_dashboards.html

No other place seems to use the modified template.

LUTECE-2170 : Add CSRF tokens to AdminDashboardJspBean actions

---

src/java/fr/paris/lutece/portal/web/dashboard/DashboardJspBean.java
src/test/java/fr/paris/lutece/portal/web/dashboard/DashboardJspBeanTest.java
src/test/java/fr/paris/lutece/portal/web/dashboard/TestDashboardComponent.java
webapp/WEB-INF/templates/admin/dashboard/manage_dashboards.html

The modified template does not seem to be used elsewhere.

LUTECE-2174 : Add CSRF protection to DashboardJspBean actions

---

src/java/fr/paris/lutece/portal/web/globalmanagement/EditorChoiceLutecePanelJspBean.java
src/test/java/fr/paris/lutece/portal/web/globalmanagement/EditorChoiceLutecePanelJspBeanTest.java
webapp/WEB-INF/templates/admin/globalmanagement/panel/editor_choice_panel.html

The modified template does not seem to be used elsewhere

LUTECE-2175 :  Add CSRF tokens to editors choice

---

src/java/fr/paris/lutece/portal/web/xsl/XslExportJspBean.java
src/test/java/fr/paris/lutece/portal/web/xsl/XslExportJspBeanTest.java
webapp/WEB-INF/templates/admin/xsl/create_xsl_export.html
webapp/WEB-INF/templates/admin/xsl/modify_xsl_export.html

Templates and JSP do not seem to be used elsewhere

LUTECE-2176 : Add CSRF protection to XslExportJspBean actions

---

src/java/fr/paris/lutece/portal/web/features/ExternalFeaturesJspBean.java
src/test/java/fr/paris/lutece/portal/web/features/ExternalFeaturesJspBeanTest.java
webapp/WEB-INF/templates/admin/features/create_external_feature.html
webapp/WEB-INF/templates/admin/features/modify_external_feature.html

The templates and JSP do not seem to be used elsewhere

LUTECE-2177 : Add CSRF tokens to ExternalFeaturesJspBean actions

---

src/java/fr/paris/lutece/util/jpa/JPAGenericDAO.java
src/test/java/fr/paris/lutece/util/jpa/JPAGenericDAOTest.java
src/test/java/fr/paris/lutece/util/jpa/TestEntityManager.java
src/test/java/fr/paris/lutece/util/jpa/TestEntityManagerFactory.java
src/test/java/fr/paris/lutece/util/jpa/TestJPAGenericDAO.java

When the entity does not exist, EntityManager#find returns null.
Is this is the case, just log it and return.

LUTECE-2208 : Do not throw an exception when removing non existent entity

---

src/java/fr/paris/lutece/portal/service/daemon/Daemon.java
src/java/fr/paris/lutece/portal/service/daemon/DaemonScheduler.java
src/test/java/fr/paris/lutece/portal/service/daemon/DaemonSchedulerTest.java
src/test/java/fr/paris/lutece/portal/service/daemon/TestDaemon.java

This allows daemons to cleanup allocated resources when they are stopped

LUTECE-2225 : Add a stop method to daemons

---

src/sql/init_db_lutece_core.sql
src/sql/upgrade/update_db_lutece_core-6.1.0-7.0.0.sql

This causes errors with some XSL librairies.

LUTECE-2299: Do not set standalone if the xml declaration is omitted

---

pom.xml

This pulls down the lastest library-lutece-unit-testing

LUTECE-2320: Update to the latest lutece-global-pom

---

src/test/java/fr/paris/lutece/portal/web/workgroup/AdminWorkgroupJspBeanTest.java
webapp/WEB-INF/templates/admin/workgroup/assign_users_workgroup.html

freemarker was confused by the use of macros inside an argument value

LUTECE-2321: Fix the box title for workgroup user assignment

---

src/java/fr/paris/lutece/portal/resources/site_messages_fr.properties
src/java/fr/paris/lutece/portal/resources/util_messages.properties
src/java/fr/paris/lutece/portal/resources/util_messages_fr.properties
webapp/WEB-INF/templates/admin/site/site_map.html
webapp/jsp/admin/ErrorPage.jsp

add i18n support for ErrorPage.jsp home buttons

add i18n support for site map home link

---

src/java/fr/paris/lutece/portal/business/progressmanager/ProgressFeed.java
src/java/fr/paris/lutece/portal/service/progressmanager/ProgressManagerService.java
src/java/fr/paris/lutece/portal/service/search/IndexationService.java
src/java/fr/paris/lutece/portal/web/progressmanager/ProgressManagerServlet.java
src/java/fr/paris/lutece/portal/web/search/SearchIndexationJspBean.java
webapp/WEB-INF/conf/core.xml
webapp/WEB-INF/templates/admin/search/search_indexation_logs.html
webapp/WEB-INF/templates/commons.html
webapp/WEB-INF/templates/commons_bs4_adminlte.html
webapp/WEB-INF/templates/commons_bs4_materialkit.html
webapp/WEB-INF/templates/commons_bs5_tabler.html
webapp/WEB-INF/templates/commons_bulma.html
webapp/js/util/progress-manager.js
webapp/themes/commons.html

add progressmanager service and use it for indexing

Lutece 2316

---

src/test/java/fr/paris/lutece/portal/service/daemon/AppDaemonServiceConcurrentTest.java
src/test/java/fr/paris/lutece/portal/service/daemon/AppDaemonServiceTest.java
src/test/java/fr/paris/lutece/portal/service/daemon/DaemonSchedulerTest.java
src/test/java/fr/paris/lutece/portal/service/file/FileServiceTest.java

LUTECE-2372 fixing errors on daemons' unit tests
LUTECE-2372 fixing errors on daemons' unit tests
LUTECE-2372 remove unused import

LUTECE-2372 fixing errors on daemons' unit tests

---

src/test/java/fr/paris/lutece/portal/service/i18n/I18nServiceTest.java

LUTECE-2442 admin user change password wrongly labelled due to i18n Unit Test changing property value

---

src/java/fr/paris/lutece/portal/resources/rbac_messages.properties
src/java/fr/paris/lutece/portal/resources/rbac_messages_fr.properties
src/java/fr/paris/lutece/portal/web/rbac/RoleManagementJspBean.java
webapp/WEB-INF/templates/admin/rbac/add_control_to_role.html
webapp/WEB-INF/templates/admin/rbac/select_permissions.html
webapp/WEB-INF/templates/admin/rbac/select_resource_ids.html

This can help the admin user conform her choices.

LUT-25910: Add context in role permission management pages

---

pom.xml
src/java/fr/paris/lutece/portal/service/daemon/AppDaemonService.java
src/java/fr/paris/lutece/portal/service/daemon/DaemonScheduler.java
src/java/fr/paris/lutece/portal/service/daemon/DaemonThreadFactory.java
src/test/java/fr/paris/lutece/portal/service/file/FileServiceTest.java
src/test/java/fr/paris/lutece/portal/service/user/menu/AdminUserMenuItemProviderRegistrarTest.java
src/test/java/fr/paris/lutece/portal/web/admin/AdminPageJspBeanTest.java
src/test/java/fr/paris/lutece/portal/web/style/PageTemplatesJspBeanTest.java
src/test/java/fr/paris/lutece/portal/web/stylesheet/StyleSheetJspBeanTest.java
src/test/java/fr/paris/lutece/portal/web/upload/UploadServletTest.java
src/test/java/fr/paris/lutece/portal/web/user/AdminUserJspBeanTest.java
src/test/java/fr/paris/lutece/portal/web/xsl/XslExportJspBeanTest.java
src/test/java/fr/paris/lutece/util/beanvalidation/BeanDefaultMessages.java
src/test/java/fr/paris/lutece/util/beanvalidation/BeanLuteceMessages.java

Integrate jakarta-concurrency to allow context propagation through the deamon treads More info https://dev.lutece.paris.fr/gitlab/archi/comite-achitecture/-/issues/99

LUT-27392 : Enable the daemons with Jakarta EE10

---

src/java/fr/paris/lutece/portal/web/insert/InsertServiceSelectorJspBean.java

https://dev.lutece.paris.fr/bugtracker/issues/26889

LUT-26889: Prevent nullPointerException if request parameter is missing

---

src/java/fr/paris/lutece/util/sql/TransactionSynchronization.java

Rollback only transaction related to current pool

LUT-27635 : JTA Transactions management and synchronization

---

src/java/fr/paris/lutece/portal/web/admin/AdminFeaturesPageJspBean.java

LUT-28144 : Fix NullPointerException on admin pages after plugin

---

src/site/site.xml

Site: Fixes "Technical Documentation" link

---

src/java/fr/paris/lutece/portal/web/stylesheet/StyleSheetJspBean.java
src/java/fr/paris/lutece/portal/web/xsl/XslExportJspBean.java

https://dev.lutece.paris.fr/bugtracker/issues/26221

LUT-26221 

---

webapp/WEB-INF/templates/admin/features/assign_users_right.html

https://dev.lutece.paris.fr/bugtracker/issues/25108

LUT-25108 : Fixed error on the filter of the AssignUsersRight.jsp page

---

src/java/fr/paris/lutece/portal/service/workflow/WorkflowService.java

LUT-29509 : Move EventAction / Type from workflow-library to lutece-core

---

src/java/fr/paris/lutece/portal/service/security/SecurityTokenFilterAdmin.java
src/java/fr/paris/lutece/portal/service/security/SecurityTokenHandler.java

filtered contain a leading slash + error message content fix

LUT-29755 : Path type keys in map containing actions that should not be filtered contain a leading slash + error message content fix

---

webapp/WEB-INF/templates/admin/themes/tabler/forms/input/input.ftl

restore LUT-29653 : Add validation message to freemarker input macro

restore LUT-29653 : Add validation message to freemarker input macro
