- src/java/fr/paris/lutece/util/PropertiesService.java
- src/test/java/fr/paris/lutece/util/PropertiesServiceTest.java
Make _properties volatile so that the swap for the new object is atomic.
Add a test to verify that removed properties are absent after a reloadAll.
> LUTECE-1873 : When reloading all properties, construct a fresh Properties object

- src/java/fr/paris/lutece/portal/service/portal/PortalMenuService.java
- src/test/java/fr/paris/lutece/portal/service/portal/PortalMenuServiceTest.java
The PortalMenuService outputs pages whose visibility depends on the user's roles,
and not on her name. Keying the cache on the role list should improve significantly
the cache hit ratio when the site is accessed by authenticated users.
Add a test checking that page visibility is respected, and that the cache returns
the same menu for the same role combination.
> LUTECE-1872 : key the PortalMenuService cache on the user's roles

- src/java/fr/paris/lutece/util/PropertiesService.java
Use commons-lang StringUtils, which provides a numeric check
which does the null check too.
this improves the performance of the method by an order of magnitude.
> LUTECE-1871 : optimize PropertiesService#getPropertyInt

- src/java/fr/paris/lutece/portal/web/xpages/SiteMapApp.java
- src/test/java/fr/paris/lutece/portal/service/portal/PortalMenuServiceTest.java
- src/test/java/fr/paris/lutece/portal/service/security/MokeLuteceAuthentication.java
- src/test/java/fr/paris/lutece/portal/web/xpages/SiteMapAppTest.java
The SiteMapApp outputs pages whose visibility depends on the user's roles,
and not on her name. Keying the cache on the role list should improve significantly
the cache hit ratio when the site is accessed by authenticated users.
Add a test checking that page visibility is respected, and that the cache returns
the same page content for the same role combination. adapt and reuse MokeLuteceAuthentication.
> Lutece 1878 : key the SiteMapApp cache on the user's roles

- src/java/fr/paris/lutece/util/PropertiesService.java
- src/test/java/fr/paris/lutece/util/PropertiesServiceTest.java
Properties files are thus reloaded in the order they were added.
Add a test which fails without the patch.
> LUTECE-1877 : Use a LinkedHashMap to preserve the insertion order

- src/java/fr/paris/lutece/portal/service/page/PageService.java
- src/java/fr/paris/lutece/portal/web/constants/Parameters.java
- src/test/java/fr/paris/lutece/portal/service/AllTests.java
- src/test/java/fr/paris/lutece/portal/service/page/PageServiceTest.java
- webapp/WEB-INF/conf/core_context.xml
This covers all usages of the base_url in the pages content, and does
not impose a strict form on the base html tag.
The method to substitute the base_url in the base tag is removed.
The impact should be minimal when the site is accessed by only one URL,
and cache size usage should be bigger when accessed by multiple URLs.
A test is added to check that cached pages contain the correct base url.
> LUTECE-1870 : intregrate the base url in the page cache key

- src/java/fr/paris/lutece/portal/resources/system_messages.properties
- src/java/fr/paris/lutece/portal/resources/system_messages_fr.properties
- src/java/fr/paris/lutece/portal/service/content/XPageAppService.java
- src/java/fr/paris/lutece/portal/service/plugin/plugin-digester-rules.xml
- src/java/fr/paris/lutece/portal/web/xpages/XPageApplicationEntry.java
- src/test/java/fr/paris/lutece/portal/service/content/XPageAppServiceTest.java
- webapp/WEB-INF/conf/core.xml
- webapp/WEB-INF/conf/lutece.properties
- webapp/WEB-INF/templates/admin/system/view_plugin.html
- webapp/css/admin/portal_admin.css
This flag can be set via a property, thus it is not necessary to duplicate the
plugin's xml file, which has no override mechanism, to disable an XPage.
> LUTECE-1925 : Allow XPages to be set as disabled in the plugin description file

- src/java/fr/paris/lutece/portal/resources/role_messages.properties
- src/java/fr/paris/lutece/portal/resources/role_messages_fr.properties
- src/java/fr/paris/lutece/portal/web/role/RoleJspBean.java
- src/test/java/fr/paris/lutece/portal/web/role/RoleJspBeanTest.java
Also add a message when request arguments are incorrect, fix a typo and
add a test verifiyng that the role name is present in the messages.
> LUTECE-1938 : add the role name to role deletion messages

- webapp/WEB-INF/templates/admin/system/modify_properties.html
This makes the order stable instead of whatever the order is from the database,
which might change at each update. This makes managing site properties easier.
> LUTECE-1947 : Sort site properties by key

- webapp/WEB-INF/conf/config.properties
Replace the default paths in config.properties by ones that
match any dev environnement : when tests are run from maven, the
working directory is the project base directory.
The paths will be updated with absolute ones when running the app, but
the config.properties file is already read at this stage.
The second run will read the customized paths.
This makes HtmlCleanerServiceTest#testClean pass because the
expected jtidy.properties is read.
> LUTECE-1967 : Change the default path in config.properties

- src/test/java/fr/paris/lutece/portal/service/PortalServiceTest.java
Use the spring mock classes that support attributes on session.
Properly initialize and reset LocalVariables.
This test should still be expanded to test more than no exceptions.
> LUTECE-1837 : Fix the PortalServiceTest#testGetDefaultPage test

- src/test/java/fr/paris/lutece/portal/service/spring/SpringContextServiceTest.java
Maybe it would be better to let that work, but this is a lot more work,
and the use case needs to be determined.
> LUTECE-1969 : Check that initializing SpringContextService twice fails

- src/test/java/fr/paris/lutece/portal/web/admin/AdminJspBeanTest.java
Use Spring MockHttpServlet which supports attributes.
Initialize LocalVariables.
Eventually, lutece-unit-testing's MokeHttpServletRequest should be fixed
to support attribtues, among other features.
> LUTECE-1970 : Fix AdminJspBeanTest#testGetAdminPagePreview

- src/test/java/fr/paris/lutece/portal/web/PortalJspBeanTest.java
Use Spring's MockHttpServletResquest which supports attributes.
Properly initialize LocalVariables.
> LUTECE-1971 : fix PortalJspBeanTest#testGetContent

- src/test/java/fr/paris/lutece/util/http/SecurityUtilTest.java
Sync it with the default configuration.
Extend LuteceTestCase so that the test can be run in isolation.
> LUTECE-1972 : Fix SecurityUtilTest#testContainsCleanParameters

- src/java/fr/paris/lutece/portal/service/security/SecurityService.java
This allows to get the same behavior is authentication is enabled then disabled
as if it is disabled from the start.
This fixes SecurityServiceTest#testLoginUser when run as part of the suite.
> LUTECE-1968 : Ensure that there is no authenticationService if authentication is disabled.

- src/java/fr/paris/lutece/portal/business/user/authentication/PasswordFactory.java
- src/test/java/fr/paris/lutece/portal/business/user/authentication/PasswordFactoryTest.java
This algorithm is supported since Java 1.8, and is more resistant to
attacks than PBKDF2WithHmacSHA1.
Downgrade PBKDF2WithHmacSHA1 to legacy status, but keep support for reading them.
> LUTECE-2025 : Use PBKDF2WithHmacSHA512 to store BO passwords

- src/java/fr/paris/lutece/portal/business/user/AdminUserHome.java
- src/test/java/fr/paris/lutece/portal/business/user/AdminUserHomeTest.java
Use an invalid password string when the password is in legacy format, so that
the token is still invalidated when the password is changed, and thus upgraded
to a proper storage format.
> LUTECE-2055 : fix reset token generation when password is in legacy format

- src/java/fr/paris/lutece/portal/service/cache/IPathCacheService.java
- src/java/fr/paris/lutece/portal/service/cache/PathCacheService.java
- src/java/fr/paris/lutece/portal/service/portal/PortalService.java
- src/test/java/fr/paris/lutece/portal/service/cache/PathCacheServiceDisabledTest.java
- src/test/java/fr/paris/lutece/portal/service/cache/PathCacheServiceEnabledTest.java
- src/test/java/fr/paris/lutece/portal/service/portal/PortalServiceTest.java
- src/test/resources/fr/paris/lutece/portal/service/portal/PortalServiceTest_getXPagePathContentWithTitleUrls_1.txt
- src/test/resources/fr/paris/lutece/portal/service/portal/PortalServiceTest_getXPagePathContent_1.txt
- src/test/resources/fr/paris/lutece/portal/service/portal/PortalServiceTest_getXPagePathContent_2.txt
- webapp/WEB-INF/conf/caches.dat
- webapp/WEB-INF/conf/core_context.xml
Cf. PR https://github.com/lutece-platform/lutece-core/pull/73
The cache is exposed via Spring, which allow plugins to replace the implementation should
the need arise. For instance, if a site uses a page_path.html template which depends on
a PageInclude which itself depends on request characteristics, it could override the implementation
to alter the cache key generation.
Tests suggest a ~6x increase in performances when the cache is enabled. Enable it by default.
Tested with a minimal XPage and the following command:
ab -c 2 -n 50000 http://localhost:8080/lutece/jsp/site/Portal.jsp?page=test
Path Cache enabled, datastore cache enabled, treemenu include disabled, XPage without extendedPathLabel
Requests per second: 4165.80 #/sec
Path Cache disabled, datastore cache enabled, treemenu …
> LUTECE-2017 : Introduce a cache for XPage path (5.x branch)

- src/java/fr/paris/lutece/portal/service/cache/IPathCacheService.java
- src/java/fr/paris/lutece/portal/service/cache/PathCacheService.java
- src/java/fr/paris/lutece/portal/service/portal/PortalService.java
- src/test/java/fr/paris/lutece/portal/service/cache/PathCacheServiceDisabledTest.java
- src/test/java/fr/paris/lutece/portal/service/cache/PathCacheServiceEnabledTest.java
- src/test/java/fr/paris/lutece/portal/service/portal/PortalServiceTest.java
- src/test/resources/fr/paris/lutece/portal/service/portal/PortalServiceTest_getXPagePathContentWithTitleUrls_1.txt
- src/test/resources/fr/paris/lutece/portal/service/portal/PortalServiceTest_getXPagePathContent_1.txt
- src/test/resources/fr/paris/lutece/portal/service/portal/PortalServiceTest_getXPagePathContent_2.txt
- webapp/WEB-INF/conf/caches.dat
- webapp/WEB-INF/conf/core_context.xml
The cache is exposed via Spring, which allow plugins to replace the implementation should
the need arise. For instance, if a site uses a page_path.html template which depends on
a PageInclude which itself depends on request characteristics, it could override the implementation
to alter the cache key generation.
Tests suggest a ~6x increase in performances when the cache is enabled. Enable it by default.
Tested with a minimal XPage and the following command:
ab -c 2 -n 50000 http://localhost:8080/lutece/jsp/site/Portal.jsp?page=test
Path Cache enabled, datastore cache enabled, treemenu include disabled, XPage without extendedPathLabel
Requests per second:    4165.80 [#/sec](mean)
Path Cache disabled, datastore cache enabled, treemenu include disabled, XPage without extendedPathLabel …
> LUTECE-2017 : Introduce a cache for XPage path

- src/java/fr/paris/lutece/portal/service/cache/CacheService.java
This makes following a cache statistics via JMX across restarts easy.
> LUTECE-2074 : Give the CacheManager a stable name. (5.x version)

- src/java/fr/paris/lutece/portal/service/cache/CacheService.java
This makes following a cache statistics via JMX across restarts easy.
> LUTECE-2074 : Give the CacheManager a stable name.

- src/java/fr/paris/lutece/portal/service/util/CryptoService.java
- src/java/fr/paris/lutece/portal/web/includes/LinksInclude.java
- src/java/fr/paris/lutece/portal/web/includes/LinksIncludeCacheService.java
- src/test/java/fr/paris/lutece/portal/web/includes/LinksIncludeCacheServiceTest.java
- src/test/java/fr/paris/lutece/portal/web/includes/LinksIncludeTest.java
- src/test/java/fr/paris/lutece/portal/web/includes/LinksIncludeTestCacheDisabled.java
- src/test/java/fr/paris/lutece/portal/web/includes/LinksIncludeTestCacheEnabled.java
- src/test/java/fr/paris/lutece/portal/web/includes/LinksIncludeTestPlugin.java
- webapp/WEB-INF/conf/caches.dat
- webapp/WEB-INF/conf/core_context.xml
- webapp/WEB-INF/templates/skin/site/plugin_css_link.html
- webapp/WEB-INF/templates/skin/site/plugin_javascript_link.html
If the file is local, compute the SHA-256 hash of its content, and append it as a query parameter to the URL of the included script or css.
While doing so, make absolute URL handling more correct (by handling https and protocol relative URLs), and more uniform between CSS and JS files.
Introduce a cache for links include to offset the cost of hash calculation.
> LUTECE-2087 : Add a token depending on content to css and js links from LinksInclude

- src/java/fr/paris/lutece/portal/service/daemon/DaemonEntry.java
- src/java/fr/paris/lutece/portal/service/daemon/DaemonThread.java
- webapp/WEB-INF/conf/core_context.xml
Daemons are reported by their names in transactions, and are grouped as "Lutece Daemon"
in Nudge's map view.
No configuration of the probe is necessary.
> LUTECE-2040 : enable tracing of Lutece daemons by Nudge

- src/sql/init_db/init_session_mysql.sql
`storage_engine` variable is deprecated since v5.5.3 of MySQL server. 
Now we should use `default_storage_engine` variable.
Please refer to [the documentation](https://dev.mysql.com/doc/refman/5.5/en/server-system-variables.html#sysvar_default_storage_engine)
> Improve compatibility with MySQL server >= 5.5.3

- src/java/fr/paris/lutece/portal/resources/system_messages.properties
- src/java/fr/paris/lutece/portal/resources/system_messages_fr.properties
- src/java/fr/paris/lutece/portal/service/daemon/AppDaemonService.java
- src/java/fr/paris/lutece/portal/service/daemon/DaemonScheduler.java
- src/java/fr/paris/lutece/portal/service/daemon/IDaemonScheduler.java
- src/java/fr/paris/lutece/portal/service/daemon/ThreadLauncherDaemon.java
- src/java/fr/paris/lutece/portal/service/mail/MailSenderDaemon.java
- src/java/fr/paris/lutece/portal/service/mail/MailService.java
- src/java/fr/paris/lutece/portal/web/system/DaemonsJspBean.java
- src/test/java/fr/paris/lutece/portal/service/daemon/DaemonSchedulerTest.java
- src/test/java/fr/paris/lutece/portal/service/daemon/TestDaemon.java
- src/test/java/fr/paris/lutece/portal/service/daemon/ThreadLauncherDaemonTest.java
- src/test/java/fr/paris/lutece/portal/web/system/DaemonsJspBeanTest.java
- webapp/WEB-INF/conf/config.properties
- webapp/WEB-INF/conf/core_context.xml
- webapp/WEB-INF/conf/daemons.properties
- webapp/WEB-INF/templates/admin/system/config_properties.html
- webapp/WEB-INF/templates/admin/system/manage_daemons.html
Add a daemon scheduler interface and implementation.
The scheduler can schedule/unschedule daemon runs, as was possible before. Add the possibility to run a daemon on demand, possibly after a delay.
Demand run and scheduled run rely on the same underlying mechanism.
Add a button to run a daemon immediately on the manage daemons page
Turn the MailSenderDaemon into a reactive one.  Enqueuing a mail signals the daemon.
Use the daemon signaling system for error recovery or rate limiting
Make the threadLauncherDaemon reactive.
Have the daemon signaled when the runnable ends.
This allows dead threads reclaiming, and execution of delayed runnable
which where blocked from execution because no slot was available for their
key.
> LUTECE-2085 : Make daemons reactive

- webapp/WEB-INF/conf/lutece.properties
Commit 85a3fedf8c046ec165dcdadcb0dcada531e3d3b2 (svn r43849) removed webapp/images/admin/page_templates and moved to images/local/skin/page_templates in commit eeb6d22cf37fb7cd9661b2f19a733f034e5838ca (svn r43873).
But the key path.image.page.template in webapp/WEB-INF/conf/lutece.properties was not updated.
> LUTECE-2128 : fix path.image.page.template default value

- src/java/fr/paris/lutece/portal/service/daemon/AppDaemonService.java
- src/test/java/fr/paris/lutece/portal/service/daemon/AppDaemonServiceTest.java
Re-registering a dameon dit not properly set all attributes of it,
most notably the running state.
This fixes the flakiness of test fr.paris.lutece.portal.service.daemon.ThreadLauncherDaemonTest.testAddItemToQueue
which would fail if run after tests that call PluginService.init, which registers daemons.
> LUTECE-2204 : Ignore attempts to re-register daemons

- src/java/fr/paris/lutece/portal/service/init/AppInit.java
When running tests, there is no ServletContext. This caused
tests to fail in the init phase of lutece.
In this case, just ignore the context path in the log message.
> LUTECE-2233 : fix startup logs in junit context

- src/java/fr/paris/lutece/util/env/EnvUtil.java
- src/test/java/fr/paris/lutece/util/env/EnvUtilTest.java
When more than one environment variable substitution is made in a string in EnvUtil.evaluate(), the offsets for the start and end of a match are incorrect, because they are indexed relative to the initial string, and not the string modified by earlier substitutions. We correct this by adjusting the offset by the accumulation of differences between the lengths of the replacement strings and the replaced strings
> Allow for multiple environment variable substitutions in a string

- src/sql/init_db_lutece_core.sql
PostreSQL does not alter the auto_increment sequence when the id is forced.
This would cause duplicate ids errors when creating pages.
> LUTECE-2297: use auto incremented core_page ids in init script

- src/sql/init_db_lutece_core.sql
PostreSQL does not alter the auto_increment sequence when the id is forced.
This would cause duplicate ids errors when creating users.
> LUTECE-2298: use auto incremented core_admin_user ids in init

- src/sql/init_db_lutece_core.sql
PostreSQL does not alter the auto_increment sequence when the id is forced.
This would cause duplicate ids errors when creating templates
> LUTECE-2302: use auto incremented core_page_template ids in init

- src/sql/init_db_lutece_core.sql
PostreSQL does not alter the auto_increment sequence when the id is forced.
This would cause duplicate ids errors when creating mailing lists.
With this, all tests pass for me on PostgreSQL.
> LUTECE-2303: use auto incremented core_admin_mailinglist ids in init

- src/test/java/fr/paris/lutece/portal/service/daemon/ThreadLauncherDaemonTest.java
250ms seems too small when executing in Jenkins. Plus it makes no sense to have a different timeout for the task and for the test.
Unfiy the timeouts, retaining the large value. Add logging to assess the time spent in the test.
> LUTECE-2305: Increase the timeout in the test

- src/test/java/fr/paris/lutece/portal/service/daemon/AppDaemonServiceConcurrentTest.java
- src/test/java/fr/paris/lutece/portal/service/daemon/TestConcurrentDaemon.java
- webapp/WEB-INF/conf/core_context.xml
- webapp/WEB-INF/conf/daemons.properties
The usage of a LinkedBlockingQueue for the executor prevented new thread from being created (see https://stackoverflow.com/questions/15485840/threadpoolexecutor-with-unbounded-queue-not-creating-new-threads).
The default being 1 thread, there could be only one daemon running at any given time.
Change to SynchronousQueue to model Executors.newCachedThreadPool()
Allow idle threads to stay around for one minute when idle, rather than killing them immediatly.
Add a test.
> LUTECE-2305: Allow daemons to run concurrently

- webapp/WEB-INF/templates/commons.html
- webapp/WEB-INF/templates/commons_bs4_adminlte.html
- webapp/WEB-INF/templates/commons_bs4_materialkit.html
- webapp/WEB-INF/templates/commons_bulma.html
- webapp/themes/commons.html
The ARIA spec says: WAI-ARIA is designed to provide semantic information about
objects when host languages lack native semantics for the object. (...) For
example, if an element with the functionality already exists, such as a checkbox
or radio button, use the native semantics of the host language. WAI-ARIA markup
is only intended to be used to enhance the native semantics (e.g., indicating
that the element is required with aria-required), or to change the semantics to
a different purpose from the standard functionality of the element.
the form tag implies the form role, and therefore should be omitted unless justified
This has the added benefit of removing a warning when validating the HTML produced by Lutece
> LUTECE-2354: Remove default role form on form tag

- src/test/java/fr/paris/lutece/portal/web/includes/LinksIncludeTest.java
- webapp/WEB-INF/plugins/document/xsl/document_spaces_tree.xsl
- webapp/WEB-INF/templates/admin/insert/insert_into_element.html
- webapp/WEB-INF/templates/admin/insert/insert_into_element2.html
- webapp/WEB-INF/templates/admin/portlet/create_portlet.html
- webapp/WEB-INF/templates/admin/portlet/modify_portlet.html
- webapp/WEB-INF/templates/admin/site/site_map.html
- webapp/WEB-INF/templates/admin/util/calendar/macro_datepicker.html
- webapp/WEB-INF/templates/admin/util/calendar/macro_datepicker_materialkit.html
- webapp/WEB-INF/templates/admin/util/calendar/macro_datetimepicker.html
- webapp/WEB-INF/templates/admin/util/editor/editor_tinymce.html
- webapp/WEB-INF/templates/commons.html
- webapp/WEB-INF/templates/commons_bs4_adminlte.html
- webapp/WEB-INF/templates/commons_bs4_materialkit.html
- webapp/WEB-INF/templates/commons_bulma.html
- webapp/WEB-INF/templates/skin/site/plugin_javascript_link.html
- webapp/WEB-INF/templates/util/calendar/macro_datepicker.html
- webapp/WEB-INF/templates/util/calendar/macro_datetimepicker.html
- webapp/WEB-INF/templates/util/editor/editor_markitupbbcode.html
- webapp/WEB-INF/xsl/normal/menu_tree.xsl
The HTML spec says for the type attribute of the script tag:
Omitting the attribute, setting it to the empty string, or setting it to a JavaScript MIME type essence match,
means that the script is a classic script, to be interpreted according to the JavaScript Script top-level
production. Classic scripts are affected by the async and defer attributes, but only when the src attribute
is set. Authors should omit the type attribute instead of redundantly setting it.
text/javascript is a JavaScript MIME type essence match, therefore type="text/javascript" should be omitted.
This has also the merit of suppressing a warning when validating the HTML produced by Lutece
> LUTECE-2353: Remove type="text/javascript" from script tag

- webapp/WEB-INF/templates/commons.html
- webapp/WEB-INF/templates/commons_bs4_adminlte.html
- webapp/WEB-INF/templates/commons_bs4_materialkit.html
- webapp/WEB-INF/templates/commons_bulma.html
- webapp/themes/commons.html
The HTML spec says: When specified on HTML elements, the id attribute value must
be unique amongst all the IDs in the element's tree and must contain at least
one character. The value must not contain any ASCII whitespace.
Thus if the id argument of the table macro is empty, the id attribute should
not be set.
> LUTECE-2355: Only add id attribute to table if not empty

- webapp/WEB-INF/templates/commons_bulma.html
The HTML spec says for the span element :
Tag omission in text/html:Neither tag is omissible.
> LUTECE-2356: Add missing closing span to bulma's sort macro

- src/java/fr/paris/lutece/portal/service/i18n/I18nService.java
Adjust javadoc, and make clear that the collection is localized in place.
> LUTECE-2462: use generics for arg as well as return type

- src/java/fr/paris/lutece/portal/business/rbac/IRBACDAO.java
- src/java/fr/paris/lutece/portal/business/rbac/RBACDAO.java
- src/java/fr/paris/lutece/portal/business/rbac/RBACHome.java
- src/java/fr/paris/lutece/portal/service/rbac/RBACService.java
- src/sql/init_db_lutece_core.sql
- src/test/java/fr/paris/lutece/portal/service/rbac/RBACServiceTest.java
- src/test/java/fr/paris/lutece/portal/service/rbac/TestRBACAction.java
- src/test/java/fr/paris/lutece/portal/service/rbac/TestUser.java
When checking RBAC authorization for collections (of RBACResource, of RBACAction or of ReferenceList), RBACService iterates over the elements of the collection and makes an SQL query for each.
This is inefficient, especially for large collections.
Switch to doing only one SQL query to pre-filter RBACs, and then using that to filter the collection
> LUT-25525: Optimize RBACService for collection checking

- webapp/WEB-INF/templates/admin/themes/corporate/forms/radio/radioButton.ftl
- webapp/WEB-INF/templates/admin/themes/tabler/forms/radio/radioButton.ftl
Adding an empty for attribute to the label element would prevent it to target the enclosed input.
> LUT-25907: Only add the label for attribute when not empty

- webapp/WEB-INF/templates/admin/system/cache_infos.html
The list of keys is displayed as an HTML list, which is more compact. HTML escape cache keys as a precaution.
> LUT-25913: Sort cache keys and use a more compact presentation

- src/java/fr/paris/lutece/portal/service/cache/AbstractCacheableService.java
- webapp/WEB-INF/templates/admin/system/cache_infos.html
Display a simple representation of statistics, equivalent to Statistics.toString()
> LUT-25914: If cache statistics are enabled, display them

- webapp/WEB-INF/conf/config.properties
- webapp/WEB-INF/templates/admin/system/config_properties.html
As per the ICalendar specifications (c.f. https://datatracker.ietf.org/doc/html/rfc2445#section-4.7.2):
- The value of the MIME message's `Content-Type` _method_ parameter must be the same as the value of the _method_ property used when building the calendar object
Currently, the value of the _method_ used when creating a new calendar invite is `REQUEST` (c.f. [ICalService class from the gru-module-workflow-appointment](https://github.com/lutece-secteur-public/gru-module-workflow-appointment/blob/db86c56304be9492f7e10f5bf408dae74e8161ce/src/java/fr/paris/lutece/plugins/workflow/modules/appointment/service/ICalService.java#L203)).
This commit will udpate the value of the MIME message's `Content-Type` _method_ parameter from `CREATE` to `REQUEST`, to match the calendar object's value.
> LUT-27083: Updated the emails' headers to properly send a calendar invite

- src/java/fr/paris/lutece/portal/business/user/authentication/PasswordFactory.java
- src/test/java/fr/paris/lutece/portal/business/user/authentication/PasswordFactoryTest.java
- webapp/WEB-INF/conf/lutece.properties
OWASP recommands 210000 iteration for PBKDF2-HMAC-SHA512
(see https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html#pbkdf2)
Password stored with less iterations are marked as legacy so that they are upgraded on next login
> Redmine-24945: Upgrade PBKDF iterations count as per OWSAP recommandations

- src/java/fr/paris/lutece/portal/service/portal/ThemesService.java
https://dev.lutece.paris.fr/bugtracker/issues/26251
This function is not used, so you can as well choose to delete it (setUserTheme L172 in ThemesService.java)
> LUT-26251 : SONAR

- src/java/fr/paris/lutece/portal/service/init/AppInitExtension.java
When units tests are executed from a plugin, the File.notExists method return false even if the resource is in a jar file and so is not available.
> LUT-29083 : Adapt AppInitExtension to the new resources loading mecanism and unit tests

- webapp/WEB-INF/templates/admin/user/attribute/image/html_code_form_attribute_image.html
admin if an image attribute exists
> LUT-29413 : Fix for User creation/modification screens unreachable in BO
